import "server-only";

import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import { env } from "@/lib/env";
import { AppError } from "@/lib/errors";
import { logger } from "@/lib/logger";

/**
 * Storage abstraction. The local driver writes to disk; an S3-compatible
 * driver can be added without touching call sites.
 */
export interface StoredObject {
  key: string;
  size: number;
  checksum: string;
  mimeType: string;
  fileName: string;
}

export interface StorageProvider {
  put(input: { fileName: string; mimeType: string; data: Buffer }): Promise<StoredObject>;
  get(key: string): Promise<{ data: Buffer; mimeType: string; fileName: string } | null>;
  delete(key: string): Promise<void>;
}

/** Extensions we are willing to store. Content is never executed or served inline. */
const ALLOWED_TYPES = new Map<string, string[]>([
  ["image/png", [".png"]],
  ["image/jpeg", [".jpg", ".jpeg"]],
  ["image/webp", [".webp"]],
  ["image/gif", [".gif"]],
  ["application/pdf", [".pdf"]],
  ["text/plain", [".txt", ".log"]],
  ["text/csv", [".csv"]],
  ["application/json", [".json"]],
  ["application/msword", [".doc"]],
  ["application/vnd.openxmlformats-officedocument.wordprocessingml.document", [".docx"]],
  ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", [".xlsx"]],
  ["application/vnd.ms-excel", [".xls"]],
  ["application/zip", [".zip"]],
  ["video/mp4", [".mp4"]],
]);

export const MAX_UPLOAD_BYTES = env.MAX_UPLOAD_MB * 1024 * 1024;
export const ALLOWED_MIME_TYPES = [...ALLOWED_TYPES.keys()];

/**
 * Validates an upload without trusting the client: extension, declared MIME
 * type and magic-byte signature must all agree.
 */
export function validateUpload(file: { name: string; type: string; size: number; data: Buffer }): {
  mimeType: string;
  extension: string;
} {
  if (file.size === 0) throw AppError.badRequest("The file is empty.");
  if (file.size > MAX_UPLOAD_BYTES) {
    throw AppError.badRequest(`The file exceeds the ${env.MAX_UPLOAD_MB} MB upload limit.`);
  }
  const extension = path.extname(file.name).toLowerCase();
  const mimeType = sniffMimeType(file.data, file.type);
  const allowedExtensions = ALLOWED_TYPES.get(mimeType);
  if (!allowedExtensions || !allowedExtensions.includes(extension)) {
    throw AppError.badRequest(`Files of type "${mimeType || file.type}" with extension "${extension}" are not accepted.`);
  }
  return { mimeType, extension };
}

function sniffMimeType(data: Buffer, declared: string): string {
  const signature = data.subarray(0, 12);
  if (signature.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return "image/png";
  if (signature[0] === 0xff && signature[1] === 0xd8 && signature[2] === 0xff) return "image/jpeg";
  if (signature.subarray(0, 4).toString("ascii") === "RIFF" && signature.subarray(8, 12).toString("ascii") === "WEBP") return "image/webp";
  if (signature.subarray(0, 3).toString("ascii") === "GIF") return "image/gif";
  if (signature.subarray(0, 4).toString("ascii") === "%PDF") return "application/pdf";
  if (signature.subarray(0, 2).toString("ascii") === "PK") {
    // DOCX/XLSX/ZIP share the ZIP container; accept the declared type when it
    // is on the allow-list, otherwise reject by returning an empty type.
    return ALLOWED_TYPES.has(declared) ? declared : "";
  }
  if (signature.subarray(4, 12).toString("ascii") === "ftypmp4") return "video/mp4";
  // Text-like formats: accept the declared type when it is on the allow-list.
  if (ALLOWED_TYPES.has(declared)) return declared;
  try {
    const text = data.subarray(0, 512).toString("utf8");
    if (/^[\x09\x0a\x0d\x20-\x7e]*$/.test(text)) return declared === "text/csv" ? "text/csv" : "text/plain";
  } catch {
    /* binary */
  }
  return "";
}

class LocalStorageProvider implements StorageProvider {
  private readonly root = path.resolve(process.cwd(), env.STORAGE_LOCAL_DIR);

  private keyToPath(key: string): string {
    // Defence in depth: keys are generated by us, but never trust path input.
    const safe = key.replace(/\.\./g, "").replace(/[^a-zA-Z0-9/_-]/g, "_");
    return path.join(this.root, safe);
  }

  async put(input: { fileName: string; mimeType: string; data: Buffer }): Promise<StoredObject> {
    const now = new Date();
    const key = `${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, "0")}/${randomUUID()}${path
      .extname(input.fileName)
      .toLowerCase()}`;
    const target = this.keyToPath(key);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, input.data, { mode: 0o640 });
    return {
      key,
      size: input.data.byteLength,
      checksum: createHash("sha256").update(input.data).digest("hex"),
      mimeType: input.mimeType,
      fileName: input.fileName,
    };
  }

  async get(key: string): Promise<{ data: Buffer; mimeType: string; fileName: string } | null> {
    try {
      const data = await readFile(this.keyToPath(key));
      return { data, mimeType: "application/octet-stream", fileName: path.basename(key) };
    } catch (error) {
      logger.warn("Attachment missing from storage", { key, error: (error as Error).message });
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.keyToPath(key));
    } catch {
      /* already gone */
    }
  }
}

class S3StorageProviderStub implements StorageProvider {
  async put(): Promise<StoredObject> {
    throw AppError.unsupported(
      "S3 storage is not configured. Set STORAGE_DRIVER=local or implement the S3 provider in src/lib/storage.",
    );
  }
  async get(): Promise<null> {
    return null;
  }
  async delete(): Promise<void> {
    /* no-op */
  }
}

export function getStorageProvider(): StorageProvider {
  return env.STORAGE_DRIVER === "s3" ? new S3StorageProviderStub() : new LocalStorageProvider();
}

export const storage = getStorageProvider();
